spring:
  application:
    name:bookEntry
  data:
    mongodb:
      uri: mongodb://nithinlinga2:Nithin@ac-e1ztx5j-shard-00-00.otzisrp.mongodb.net:27017,ac-e1ztx5j-shard-00-01.otzisrp.mongodb.net:27017,ac-e1ztx5j-shard-00-02.otzisrp.mongodb.net:27017/?replicaSet=atlas-xywy94-shard-0&ssl=true&authSource=admin
      post: 27017
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nithinlinga46@gmail.com
    password: irqy mdmq iylb ghxl
    properties:
      mail:
        smtp:
          auth: true
          starttles:
            enable: true
weather_api_key: f46e4ea18951abbdb90ccb30fd064c2b